{
 "title": "Netology",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}\r[1m])) * 100)",
     "legendFormat": "CPU used %"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "LA1" },
    { "expr": "node_load5", "legendFormat": "LA5" },
    { "expr": "node_load15", "legendFormat": "LA15" }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "Free memory %"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sdc\"} * 100 / node_filesystem_size_bytes{device=\"/dev/sdc\"}",
     "legendFormat": "Free space %"
    }
   ]
  }
 ]
}