apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deploy
  namespace: app-namespace
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 80
