FROM centos:7

RUN adduser elasticsearch

COPY ./elasticsearch.tar.gz / 

RUN mkdir elasticsearch && \
    tar -xzf elasticsearch.tar.gz -C elasticsearch --strip-components 1 && \
    mkdir -p /var/lib/elasticsearch/db-data /var/lib/elasticsearch/db-logs && \
    chown -R elasticsearch:elasticsearch /elasticsearch && \
    chown -R elasticsearch:elasticsearch /var && \
    rm -rf elasticsearch.tar.gz

USER elasticsearch:elasticsearch

WORKDIR /elasticsearch

CMD ["./bin/elasticsearch"]