Vagrant.configure("2") do |config|
  
  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.box = "bento/ubuntu-20.04"
    elasticsearch.vm.network "private_network", ip: "10.0.1.2"
    elasticsearch.vm.hostname = "elasticsearch"
  end

  config.vm.define "kibana" do |kibana|
    kibana.vm.box = "bento/ubuntu-20.04"
    kibana.vm.network "private_network", ip: "10.0.1.3"
    kibana.vm.hostname = "kibana"
  end

end
